_main_condition_mapping: dict[str, list[str]] = {
    "0": ["ability_description_instant_trigger_kind_first_flip"],
    "1": [
        "ability_description_n_times",
        "ability_description_instant_trigger_kind_power_flip",
    ],
    "100": [
        "ability_description_n_times",
        "ability_description_instant_trigger_kind_skill_hit",
    ],
    "13": [],
    "131": [],
    "132": [],
    "136": [],
    "137": [],
    "14": [],
    "15": [],
    "16": [],
    "18": ["ability_description_instant_trigger_kind_skill_invoke"],
    "19": ["ability_description_instant_trigger_kind_skill_max"],
    "2": [],
    "20": [],
    "22": [],
    "23": [],
    "24": [],
    "3": [
        "ability_description_n_times",
        "ability_description_instant_trigger_kind_ball_flip",
    ],
    "4": ["ability_description_instant_trigger_kind_fever"],
    "45": [],
    "46": [],
    "5": [],
    "50": ["ability_description_instant_trigger_kind_member"],
    "51": [],
    "56": [],
    "57": [],
    "58": ["ability_description_instant_trigger_kind_power_flip_lv"],
    "59": [],
    "6": ["ability_description_instant_trigger_kind_enemy_kill"],
    "63": [],
    "7": ["ability_description_instant_trigger_kind_combo"],
    "70": [],
    "8": [],
}

_main_effect_mapping: dict[str, list[str]] = {
    "0": [
        "ability_description_for_second",
        "ability_description_common_content_attack",
    ],
    "1": ["ability_description_common_content_skill_damage"],
    # NOTE: Currently this is hard-coded to Fire Resistance Debuff. Only AHanabi has this.
    "107": ["ability_description_common_content_condition_slayer"],
    "112": [],
    "116": [],
    "117": [],
    "118": [],
    "123": [],
    "144": [],
    # NOTE: This ALWAYS uses Power Flip Lv3.
    "152": ["ability_description_common_content_power_flip_damage_lv"],
    "155": [],
    # NOTE: This ALWAYS sets "Attack Buff" as the condition.
    "156": ["ability_description_common_content_condition_extend"],
    "158": [],
    "16": [],
    "162": [],
    "164": [],
    "17": [],
    "176": [],
    "189": [],
    "190": [],
    "191": [],
    "193": [],
    "195": [],
    "196": [],
    "198": ["ability_description_common_content_power_flip_combo_count_down"],
    "199": [],
    "2": [],
    "201": [],
    "203": ["ability_description_instant_content_hp"],
    "204": [],
    "207": [],
    "209": ["ability_description_instant_content_skill_gauge"],
    "21": [],
    "211": [],
    "212": [],
    "218": [],
    "221": [],
    "222": [],
    "224": [],
    "225": [],
    "24": [],
    "243": ["ability_description_common_content_second_skill_gauge"],
    "245": [],
    "249": ["ability_description_instant_content_enemy_damage"],
    "251": [],
    "253": [],
    "26": [
        "ability_description_for_second",
        "ability_description_condition_content_piercing",
    ],
    "265": [],
    "27": [],
    "28": [
        "ability_description_for_second",
        "ability_description_common_content_power_flip_damage",
    ],
    "289": [],
    "307": [],
    "31": ["ability_description_common_content_attack"],
    "32": [],
    "33": ["ability_description_common_content_skill_damage"],
    "330": [],
    "34": [],
    "35": [],
    "354": [],
    "36": [],
    "366": [],
    "37": [],
    "38": [],
    "386": [],
    "388": [],
    "389": [],
    "39": [],
    "391": [],
    "4": [],
    "40": [],
    "41": [],
    "411": [],
    "459": [],
    "460": [],
    "466": [],
    "468": [],
    "487": [],
    "489": [],
    "49": ["ability_description_common_content_fever_point"],
    "5": [],
    "50": [],
    "501": [],
    "503": [],
    "504": [],
    "505": [],
    "506": [],
    "51": [],
    "510": ["ability_description_common_content_condition_slayer"],
    "512": [],
    "518": [],
    "52": [],
    "522": [],
    "525": [],
    "533": [],
    "54": ["ability_description_common_content_power_flip_damage"],
    "55": [],
    "58": [],
    "61": [],
    "66": [],
    "67": [],
    "68": [],
    "69": [],
    "7": [],
    "8": [],
    "95": [],
    "98": [],
}

_continuous_condition_mapping: dict[str, list[str]] = {
    "5": ["ability_description_during_trigger_kind_multiball"],
    "8": ["ability_description_during_trigger_kind_condition"],
    "105": ["ability_description_during_trigger_kind_skill_gauge_high"],
}

_continuous_effect_mapping: dict[str, list[str]] = {
    "0": ["ability_description_common_content_attack"],
    "3": ["ability_description_common_content_skill_gauge_chaging"],
    # NOTE: Direct hits number (so far) is always hardcoded to 2.
    "45": ["ability_description_common_content_aditional_direct_attack_and_damage"],
}
